### ISSUE TITLE
Multiple articles exist for the same topic, but no general article exists

### ISSUE THREAD

**Issue by BendixSpring** [TeamMentor/Master#954]
Many times there are language-specific articles on a given topic that should actually have an article that applies to all languages.  For example:
![image](https://cloud.githubusercontent.com/assets/3578332/6809416/839f284e-d230-11e4-9bc5-9e5dcc9201e5.png)
Do Not Cache Sensitive Data could easily apply to all languages.  There should be an article for all languages and have references to the other language specific articles.

So when a person does a generic search, they would miss this article unless they specifically hit the right filter.

**Comment by roman87** [comment]
This is a general issue that is really hard to solve at this point. Basically there are a lot of articles where information is duplicated, because it is general information. And the only thing that is different is some technology specific paragraphs. We do  have Vulnerability articles (which are not in the Index yet) that sort of address the issue. They provide technology agnostic content with further links to technology specific articles.
. Do feel free to open a specific content issue if you feel that there should be a generic article. (Like you example above. Please one issue per example :)

**Comment by BendixSpring** [comment]
I think in order to maximize usefulness to the end user, having general articles that apply to all languages is important.  It could really simplify the number of results returned if the system responded with the general article along with the few language-specific implementation articles.
